package br.com.filarmonica.view.financeiro;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * FORMULÁRIO DE REGISTRO DE PAGAMENTOS E FINANÇAS
 * @author Marcelo Augusto
 */
public class FormFinancas extends javax.swing.JInternalFrame {
    
    FormFinancasActionListener listener;
    
    public FormFinancas() {
        initComponents();
        listener = new FormFinancasActionListener(this);
    }

    public JLabel getLabelDividaMusico() {
        return labelDividaMusico;
    }

    public void setLabelDividaMusico(JLabel labelDividaMusico) {
        this.labelDividaMusico = labelDividaMusico;
    }

    public JLabel getLabelTotalReceber() {
        return labelTotalReceber;
    }

    public void setLabelTotalReceber(JLabel labelTotalReceber) {
        this.labelTotalReceber = labelTotalReceber;
    }

    public JLabel getLabelTotalCaixa() {
        return labelTotalCaixa;
    }

    public void setLabelTotalCaixa(JLabel labelTotalCaixa) {
        this.labelTotalCaixa = labelTotalCaixa;
    }
    
    public JPanel getPanelDividaMusico() {
        return panelDividaMusico;
    }

    public void setPanelDividaMusico(JPanel panelDividaMusico) {
        this.panelDividaMusico = panelDividaMusico;
    }

    public JTable getTableDebitos() {
        return tableDebitos;
    }

    public void setTableDebitos(JTable tableDebitos) {
        this.tableDebitos = tableDebitos;
    }

    public JTable getTableMusicos() {
        return tableMusicos;
    }

    public void setTableMusicos(JTable tableMusicos) {
        this.tableMusicos = tableMusicos;
    }

    public JTextField getTextFieldPesquisarMusico() {
        return textFieldPesquisarMusico;
    }

    public void setTextFieldPesquisarMusico(JTextField textFieldPesquisarMusico) {
        this.textFieldPesquisarMusico = textFieldPesquisarMusico;
    }

    public JButton getButtonAddPagamento() {
        return buttonAddPagamento;
    }

    public void setButtonAddPagamento(JButton buttonAddPagamento) {
        this.buttonAddPagamento = buttonAddPagamento;
    }

    public JButton getButtonGerarPDF() {
        return buttonGerarPDF;
    }

    public void setButtonGerarPDF(JButton buttonGerarPDF) {
        this.buttonGerarPDF = buttonGerarPDF;
    }
    
    public void setCenterPosition() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPesquisa = new javax.swing.JLabel();
        textFieldPesquisarMusico = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDebitos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMusicos = new javax.swing.JTable();
        buttonAddPagamento = new javax.swing.JButton();
        buttonGerarPDF = new javax.swing.JButton();
        panelDividaMusico = new javax.swing.JPanel();
        labelDividaMusico = new javax.swing.JLabel();
        panelTotalCaixa = new javax.swing.JPanel();
        labelTotalCaixa = new javax.swing.JLabel();
        panelTotalReceber = new javax.swing.JPanel();
        labelTotalReceber = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Central de Finanças");

        labelPesquisa.setText("Pesquisar:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Últimos débitos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        tableDebitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableDebitos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Músicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        tableMusicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableMusicos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        buttonAddPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/filarmonica/images/payment.png"))); // NOI18N
        buttonAddPagamento.setToolTipText("Realizar pagamento");
        buttonAddPagamento.setActionCommand("Pagamento");
        buttonAddPagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAddPagamento.setEnabled(false);

        buttonGerarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/filarmonica/images/pdf_2.png"))); // NOI18N
        buttonGerarPDF.setToolTipText("Exportar para PDF");
        buttonGerarPDF.setActionCommand("PDF");
        buttonGerarPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonGerarPDF.setEnabled(false);

        panelDividaMusico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "À receber de {Musico}", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        labelDividaMusico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDividaMusico.setText("R$ 0,00");
        labelDividaMusico.setToolTipText("Caso o valor seja negativo, o músico estará com crédito.");

        javax.swing.GroupLayout panelDividaMusicoLayout = new javax.swing.GroupLayout(panelDividaMusico);
        panelDividaMusico.setLayout(panelDividaMusicoLayout);
        panelDividaMusicoLayout.setHorizontalGroup(
            panelDividaMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDividaMusicoLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(labelDividaMusico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDividaMusicoLayout.setVerticalGroup(
            panelDividaMusicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDividaMusicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDividaMusico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTotalCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total em Caixa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        labelTotalCaixa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTotalCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/filarmonica/images/register.png"))); // NOI18N
        labelTotalCaixa.setText("R$ 0,00");

        javax.swing.GroupLayout panelTotalCaixaLayout = new javax.swing.GroupLayout(panelTotalCaixa);
        panelTotalCaixa.setLayout(panelTotalCaixaLayout);
        panelTotalCaixaLayout.setHorizontalGroup(
            panelTotalCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalCaixaLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(labelTotalCaixa)
                .addGap(56, 56, 56))
        );
        panelTotalCaixaLayout.setVerticalGroup(
            panelTotalCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalCaixaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTotalCaixa)
                .addContainerGap())
        );

        panelTotalReceber.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total a receber", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        labelTotalReceber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTotalReceber.setText("R$ 0,00");

        javax.swing.GroupLayout panelTotalReceberLayout = new javax.swing.GroupLayout(panelTotalReceber);
        panelTotalReceber.setLayout(panelTotalReceberLayout);
        panelTotalReceberLayout.setHorizontalGroup(
            panelTotalReceberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalReceberLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(labelTotalReceber)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        panelTotalReceberLayout.setVerticalGroup(
            panelTotalReceberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalReceberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotalReceber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDividaMusico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonAddPagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonGerarPDF)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(textFieldPesquisarMusico, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelPesquisa))))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(panelTotalReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTotalCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonAddPagamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonGerarPDF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldPesquisarMusico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDividaMusico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotalCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotalReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddPagamento;
    private javax.swing.JButton buttonGerarPDF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDividaMusico;
    private javax.swing.JLabel labelPesquisa;
    private javax.swing.JLabel labelTotalCaixa;
    private javax.swing.JLabel labelTotalReceber;
    private javax.swing.JPanel panelDividaMusico;
    private javax.swing.JPanel panelTotalCaixa;
    private javax.swing.JPanel panelTotalReceber;
    private javax.swing.JTable tableDebitos;
    private javax.swing.JTable tableMusicos;
    private javax.swing.JTextField textFieldPesquisarMusico;
    // End of variables declaration//GEN-END:variables
}
