package br.com.filarmonica.view.frequencia;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;


public class FormFrequencia extends javax.swing.JInternalFrame {

    FormFrequenciaActionListener listener;
    public FormFrequencia() {
        initComponents();
        listener = new FormFrequenciaActionListener(this);
    }

    public JLabel getLabelValueFaults() {
        return labelValueFaults;
    }

    public void setLabelValueFaults(JLabel labelValueFaults) {
        this.labelValueFaults = labelValueFaults;
    }

    public JRadioButton getRadioButtonFalta() {
        return radioButtonFalta;
    }

    public void setRadioButtonFalta(JRadioButton radioButtonFalta) {
        this.radioButtonFalta = radioButtonFalta;
    }

    public JRadioButton getRadioButtonPresenca() {
        return radioButtonPresenca;
    }

    public void setRadioButtonPresenca(JRadioButton radioButtonPresenca) {
        this.radioButtonPresenca = radioButtonPresenca;
    }

    public JButton getButtonReleaseCombo() {
        return buttonReleaseCombo;
    }

    public void setButtonReleaseCombo(JButton buttonReleaseCombo) {
        this.buttonReleaseCombo = buttonReleaseCombo;
    }

    public JButton getButtonAddTo() {
        return buttonAddTo;
    }

    public void setButtonAddTo(JButton buttonAddTo) {
        this.buttonAddTo = buttonAddTo;
    }
    
    public JButton getButtonFinalizar() {
        return buttonFinalizar;
    }

    public void setButtonFinalizar(JButton buttonFinalizar) {
        this.buttonFinalizar = buttonFinalizar;
    }

    public JComboBox<String> getComboMusicos() {
        return comboMusicos;
    }

    public void setComboMusicos(JComboBox<String> comboMusicos) {
        this.comboMusicos = comboMusicos;
    }

    public JComboBox<String> getComboTocatas() {
        return comboTocatas;
    }

    public void setComboTocatas(JComboBox<String> comboTocatas) {
        this.comboTocatas = comboTocatas;
    }

    public JTable getTableFrequencia() {
        return tableFrequencia;
    }

    public void setTableFrequencia(JTable tableFrequencia) {
        this.tableFrequencia = tableFrequencia;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelTocata = new javax.swing.JLabel();
        comboTocatas = new javax.swing.JComboBox<>();
        labelMusicos = new javax.swing.JLabel();
        comboMusicos = new javax.swing.JComboBox<>();
        buttonAddTo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        radioButtonPresenca = new javax.swing.JRadioButton();
        radioButtonFalta = new javax.swing.JRadioButton();
        buttonReleaseCombo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFrequencia = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        buttonFinalizar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        labelValueFaults = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Frequência");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTocata.setText("Tocata:");

        comboTocatas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        labelMusicos.setText("Componentes:");

        comboMusicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        buttonAddTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/filarmonica/images/add-to-list.png"))); // NOI18N
        buttonAddTo.setToolTipText("Adicionar a folha de frequênicia");
        buttonAddTo.setActionCommand("AddTo");
        buttonAddTo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(radioButtonPresenca);
        radioButtonPresenca.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        radioButtonPresenca.setText("PRESENTE");
        radioButtonPresenca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(radioButtonFalta);
        radioButtonFalta.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        radioButtonFalta.setText("FALTOU");
        radioButtonFalta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(radioButtonPresenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonFalta)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonPresenca)
                    .addComponent(radioButtonFalta))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        buttonReleaseCombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/filarmonica/images/cancel_16x16.png"))); // NOI18N
        buttonReleaseCombo.setToolTipText("Cancelar");
        buttonReleaseCombo.setActionCommand("Liberar");
        buttonReleaseCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReleaseCombo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMusicos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTocata, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAddTo))
                    .addComponent(comboMusicos, 0, 295, Short.MAX_VALUE)
                    .addComponent(comboTocatas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonReleaseCombo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTocata)
                    .addComponent(comboTocatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReleaseCombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMusicos)
                    .addComponent(comboMusicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonAddTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonReleaseCombo, comboMusicos, comboTocatas});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela de frequência da tocata", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        tableFrequencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableFrequencia);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        buttonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/filarmonica/images/list-accept.png"))); // NOI18N
        buttonFinalizar.setToolTipText("Finalizar lista");
        buttonFinalizar.setActionCommand("Finalizar");
        buttonFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonFinalizar)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonFinalizar)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        labelValueFaults.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelValueFaults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelValueFaults.setText("R$ 0,00");
        labelValueFaults.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelValueFaults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelValueFaults, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        setBounds(0, 0, 600, 546);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddTo;
    private javax.swing.JButton buttonFinalizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonReleaseCombo;
    private javax.swing.JComboBox<String> comboMusicos;
    private javax.swing.JComboBox<String> comboTocatas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMusicos;
    private javax.swing.JLabel labelTocata;
    private javax.swing.JLabel labelValueFaults;
    private javax.swing.JRadioButton radioButtonFalta;
    private javax.swing.JRadioButton radioButtonPresenca;
    private javax.swing.JTable tableFrequencia;
    // End of variables declaration//GEN-END:variables
}
